# -*- coding: utf-8 -*-
"""solucion_banda_musica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOTfjQlNrrpRxhgHR0Jv0uCs9JyPjOAF

# Ejercicio: Banda de música (Clases, herencia y composición)

Este notebook implementa la solución paso a paso, mostrando:

- **Clase base** `Instrumento` (atributos y métodos comunes).
- **Herencia**: `Guitarra` → `GuitarraElectrica`.
- **Composición**: `Bateria` contiene **dos** `Platillo` (objetos dentro de otro objeto).
- **Composición a mayor escala**: `BandaMusica` contiene instrumentos y los coordina.

## 1) Diseño (qué vamos a construir)

1. **Instrumento**
   - Atributos: `nombre`, `tipo`
   - Métodos: `afinar()` y `tocar()` → devuelven `str`

2. **Guitarra** (hereda de `Instrumento`)
   - Atributo extra: `num_cuerdas`
   - Debe recordar si está **afinada** (`afinada: bool`)
   - `tocar()` *solo funciona* si está afinada

3. **GuitarraElectrica** (hereda de `Guitarra`)
   - Atributo extra: `potencia`
   - `tocar()` indica que está tocando la guitarra eléctrica y su `nombre`

4. **Platillo**
   - Clase simple para representar un platillo (p.ej. `nombre` / `tipo`)

5. **Bateria**
   - Atributo: `marca`
   - Contiene `platillo_1` y `platillo_2` (instancias de `Platillo`) → **composición**

6. **BandaMusica**
   - Atributos: `nombre_banda`, `guitarra`, `guitarra_electrica`, `bateria`
   - Métodos: `afinar_instrumentos()` y `tocar_instrumentos()` que coordinan a todos

## Explicación de la declaración de métodos y su uso con parámetros nombrados
"""

def funcion1(texto: str, numero: int=1,  color:str = "rojo") -> str:
    return (texto + color)*numero

print(funcion1(color="azul", texto="Hola", numero=2))

print("Hola"*3)

class Instrumento:
    """Clase base para instrumentos.

    - nombre: nombre del instrumento (p.ej. 'Fender Stratocaster')
    - tipo: tipo de instrumento (p.ej. 'cuerda', 'percusión')
    """

    def __init__(self, nombre: str, tipo: str) -> None:
        self.nombre = nombre
        self.tipo = tipo
        self.afinado = False

    def afinar(self) -> str:
        self.afinado = True
        return f"Afinando {self.tipo} '{self.nombre}'."

    def tocar(self) -> str:
        return f"Tocando {self.tipo} '{self.nombre}'."

"""## 2) Herencia: Guitarra

- Hereda de `Instrumento`.
- Añade `num_cuerdas`.
- Añade el estado `afinada` para controlar si puede tocar.

"""

class Guitarra(Instrumento):
    """Guitarra acústica o genérica.
    - Solo permite tocar si está afinada.
    """
    def __init__(self, nombre: str, num_cuerdas: int) -> None:
        super().__init__(nombre=nombre, tipo="cuerda")
        self.num_cuerdas = num_cuerdas

    def afinar(self) -> str:
        return f"Afinando guitarra '{self.nombre}' ({self.num_cuerdas} cuerdas)."

    def tocar(self) -> str:
        if not self.afinado:
            return f"No se puede tocar la guitarra '{self.nombre}': está desafinada."
        return f"Tocando guitarra '{self.nombre}' ({self.num_cuerdas} cuerdas)."

"""## 3) Herencia: Guitarra eléctrica

- Hereda de `Guitarra`.
- Añade `potencia`.
- Sobrescribe `tocar()` con un mensaje específico.

"""

class GuitarraElectrica(Guitarra):
    """Guitarra eléctrica: es una guitarra, pero con potencia."""

    def __init__(self, nombre: str, num_cuerdas: int, potencia: int) -> None:
        super().__init__(nombre=nombre, num_cuerdas=num_cuerdas)
        self.potencia = potencia

    def tocar(self) -> str:
        if not self.afinado:
            return f"No se puede tocar la guitarra eléctrica '{self.nombre}': está desafinada."
        return f"Tocando guitarra eléctrica '{self.nombre}' con potencia {self.potencia}W."

"""## 4) Composición: Platillo y Batería

Aquí usamos **composición**:  
`Bateria` **tiene** (contiene) dos objetos `Platillo` en lugar de heredar de ellos.

"""

class Platillo(Instrumento):
    """Representa un platillo de una batería."""

    def __init__(self, nombre: str) -> None:
        self.nombre = nombre

    def tocar(self) -> str:
        return f"Golpeando el platillo '{self.nombre}'."


class Bateria(Instrumento):
    """Batería: instrumento de percusión que contiene platillos (composición)."""

    def __init__(self, marca: str, platillo_1: Platillo, platillo_2: Platillo) -> None:
        super().__init__(nombre=marca, tipo="percusión")
        self.marca = marca
        self.platillo_1 = platillo_1
        self.platillo_2 = platillo_2


    def afinar(self) -> str:
        return f"Ajustando/afinando batería '{self.marca}' y revisando platillos."

    def tocar(self) -> str:
        if not self.afinado:
            return f"No se puede tocar la batería '{self.marca}': aún no está preparada (afinada)."
        # Además de tocar la batería, tocamos los platillos.
        return (
            f"Tocando batería '{self.marca}'.\n"
            f" - {self.platillo_1.tocar()}\n"
            f" - {self.platillo_2.tocar()}"
        )

"""## 5) Banda de música

`BandaMusica` coordina a los instrumentos que **contiene** (composición a nivel de banda).  
Tiene métodos para:

- `afinar_instrumentos()` → afina todo
- `tocar_instrumentos()` → toca todo

"""

class BandaMusica:
    def __init__(self, nombre_banda: str, guitarra: Guitarra,
                 guitarra_electrica: GuitarraElectrica, bateria: Bateria) -> None:
        self.nombre_banda = nombre_banda
        self.guitarra = guitarra
        self.guitarra_electrica = guitarra_electrica
        self.bateria = bateria

    def afinar_instrumentos(self) -> str:
        acciones = [
            f"Banda '{self.nombre_banda}' afinando instrumentos:",
            f" - {self.guitarra.afinar()}",
            f" - {self.guitarra_electrica.afinar()}",
            f" - {self.bateria.afinar()}",
        ]
        return "\n".join(acciones)

    def tocar_instrumentos(self) -> str:
        acciones = [
            f"Banda '{self.nombre_banda}' tocando:",
            f" - {self.guitarra.tocar()}",
            f" - {self.guitarra_electrica.tocar()}",
            f" - {self.bateria.tocar()}",
        ]
        return "\n".join(acciones)

"""## 6) Prueba final (crear la banda, afinar y tocar)

Creamos objetos y probamos:

1. Intentar tocar **antes** de afinar (para ver las restricciones).
2. Afinar.
3. Tocar.

"""

# 1) Creamos instrumentos
guitarra = Guitarra(nombre="Yamaha F310", num_cuerdas=6)
guitarra_e = GuitarraElectrica(nombre="Ibanez RG", num_cuerdas=6, potencia=50)

platillo_a = Platillo(nombre="Crash")
platillo_b = Platillo(nombre="Ride")
bateria = Bateria(marca="Pearl", platillo_1=platillo_a, platillo_2=platillo_b)

# 2) Creamos la banda
banda = BandaMusica(
    nombre_banda="Los PythonRockers",
    guitarra=guitarra,
    guitarra_electrica=guitarra_e,
    bateria=bateria
)

# Intento de tocar antes de afinar
print(banda.tocar_instrumentos())
print("\n" + "-"*60 + "\n")

# Afinamos y tocamos
print(banda.afinar_instrumentos())
print("\n" + "-"*60 + "\n")
print(banda.tocar_instrumentos())